pipeline {
    agent any

    stages {
      stage('Cleaning the directory') {
        steps {
          sh 'rm -rf *'
        }
      }
      stage('Clone Production') {
        steps {
          sh '''
          mkdir warnerproduction
          cd warnerproduction
          git clone https://github.com/Aatmaani-org/Production.git
          '''
        }
      }
      stage('Clone Devops') {
         steps {
           sh '''
           mkdir warnerdevops
           cd warnerdevops
           git clone https://github.com/Aatmaani-org/Devops.git
         '''  
         }
      }
      stage('Build and push the image to ECR') {
        steps {
          sh '''
          cd warnerdevops/Devops/Sooraj
          bash build_push.sh
          '''
        }
      }
      stage('Helm') {
         steps {
           sh '''
           cd warnerdevops/Devops/Sooraj/helm
           helm upgrade --install --set image.tag=dev-latest warnerbro warnerbros -n dev -f values-dev.yaml
           '''
         }
      }
      stage('Build and push the image to ECR') {
        steps {
          sh 'bash qa_tag.sh'
        }
      }
    }
    post {
      failure {
        slackSend channel: ' project-team', message: 'job failed'
      }
      success {
        slackSend channel: ' project-team', message: 'job Success'
      }
    }
}
