pipeline {
    agent any

    stages {
      stage('Clone Production') {
        steps {
          git branch: 'main', url: 'https://github.com/Aatmaani-org/Production.git'
        }
      }
      stage('Build and push the image to ECR') {
        steps {
          sh '''
	  docker build -t new-nodejs .
          docker tag new-nodejs:latest 883195043912.dkr.ecr.us-west-2.amazonaws.com/new-nodejs:latest
          docker push 883195043912.dkr.ecr.us-west-2.amazonaws.com/new-nodejs:latest 
          '''
        }
      }
      stage('Clone Devops') {
         steps {
           git branch: 'main', url: 'https://github.com/Aatmaani-org/Devops.git'
         }
      }
      stage('Helm') {
         steps {
           sh 'ls'
           sh 'pwd'
           sh 'helm upgrade --install warnerbro warnerbros -n dev -f Sooraj/helm/values-dev.yaml
         }
      }
    }
}
