pipeline {
  agent any
  
  stages {
    stage ('Git clone') {
      steps{
        git branch: 'main', url:'https://github.com/Aatmaani-org/Production.git'
      }
    }

    stage ('Build Images') {
      steps{
        sh 'docker build -t node-app --build-arg GIT_COMMIT=$(git log -1 --format=%h) .'
     }
    }

    stage ('Push image to ECR') {
      steps{
        sh ''' docker tag node-app 883195043912.dkr.ecr.us-west-2.amazonaws.com/nodejs-repository-dev:node-app-$(git log -1 --format=%h)
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 883195043912.dkr.ecr.us-west-2.amazonaws.com
        docker push 883195043912.dkr.ecr.us-west-2.amazonaws.com/nodejs-repository-dev:node-app-$(git log -1 --format=%h)
        cd
        '''
      }
    }
    
    stage ('creating Dir') {
      steps{
      sh ''' mkdir jenkins
      cd jenkins
      git clone https://github.com/Aatmaani-org/Devops.git
      '''
      }
    }
    
    stage ('Creating pod using Helm') {
      steps{
        sh ''' cd jenkins
        cd Devops/Machendra/helm/
        helm upgrade --install node-dev marvel -n dev -f values-dev.yaml
        '''
        }
      }
    }
    
    post {
      failure {
        slackSend channel: "project-team", color: 'danger', message: "Build Status: Failure ${env.JOB_NAME} ${env.BUILD_NUMBER} ${env.BUILD_URL}"
        }
      
      success {
        slackSend channel: "project-team", color: 'good', message: "Build Status: Success ${env.JOB_NAME} ${env.BUILD_NUMBER} ${env.BUILD_URL}"
        }
      
      
    }
  }

 
