pipeline {
  agent any
  
  stages {
    stage ('Git clone') {
      steps{
        git branch: 'main', url:'https://github.com/Aatmaani-org/Production.git'
      }
    }
    
    stage ('Build Images') {
      steps{
        sh 'docker build -t node-app --build-arg GIT_COMMIT=$(git log -1 --format=%h) .'
     }
    }

    
    stage ('creating Dir') {
      steps{
      sh ''' rm -rf jenkins
      mkdir jenkins
      cd jenkins
      git clone https://github.com/Aatmaani-org/Devops.git
      '''
      }
    }    
    
    stage ('Push image to ECR and Creating pod using Helm') {
      steps{
        sh ''' pwd
        ls 
        cd jenkins/Devops/Machendra/
        bash pushimageToecr.sh
        '''
     }
    }
    
    stage ('Pull image to ECR and Creating pod using Helm in QA') {
      steps{
        sh ''' cd jenkins/Devops/Machendra/
        bash pullimageECR.sh
        '''
     }
    } 
     

  }
    post {
      failure {
        slackSend channel: "project-team", color: 'danger', message: "Build Status: Failure ${env.JOB_NAME} ${env.BUILD_NUMBER} ${env.BUILD_URL}"
        }
      
      success {
        slackSend channel: "project-team", color: 'good', message: "Build Status: Success ${env.JOB_NAME} ${env.BUILD_NUMBER} ${env.BUILD_URL}"
        }
      
    }
  }

 
